### ISSUE TITLE
Define paths with regex

### ISSUE THREAD

**Issue by mdelapenya** [mdelapenya/probot-codeowners-labeller#8]
I'd say if that particular use case is required then the regex is likely the best option.

Maybe the below format could be the one to support glob and regex in the future:

```
- label
   - <pattern>
       - type: (glob|regex)  glob is the default value
```

```
- "label1"
  - "A/to/[0-9]+.t*t"
      - type: regex
- "label2"              # to include all the files in A/to/* but exclude A/to/foo*
  - "A/to/(?!foo).*"
      - type: regex
- "label3"
  - "**/*.foo"
- "label4"
  - "**/*.bar"
      - type: glob
```

The below test strings might help to understand that particular use case:
![image](https://user-images.githubusercontent.com/2871786/71517329-d10d8980-28ad-11ea-95ca-d3ddc494ee0f.png)

For the time being, I'd say we don't need to think about that particular use case now

_Originally posted by @v1v in https://github.com/mdelapenya/probot-codeowners-labeller/pull/7#issuecomment-569261317_

**Comment by mdelapenya** [comment]
Hey @v1v, what do you think about this structure?
```yaml
- label
   - <type (glob|regex)>: <pattern>
```
That would simplify the YAML file I guess:

```yaml
- "label1"
  - regex: "A/to/[0-9]+.t*t"
- "label2"              # to include all the files in A/to/* but exclude A/to/foo*
  - regex: "A/to/(?!foo).*"
- "label3"
  - glob: "**/*.foo"
- "label4"
  - glob: "**/*.bar"
```
